# This is the config file for GPII Helm Charts.
#
# It contain a list of chart names with respect to install/uninstall order.
# All charts are being installed from /common/charts directory, which
# is shared between AWS and GCP parts of the project.
#
# Child directory named "values" may contain ERB template with custom values
# for the chart, that is being rendered in `rake generate` task.
#
# Every chart should have the following attributes:
#
# beautiful-chart:
#  release_name: release-name-to-pass-to-helm
#  release_namespace: release-namespace-to-pass-to-helm
#

# TODO: switch couchdb deployment to Helm chart
# couchdb:
#   release_name: couchdb
#   release_namespace: gpii
nginx-ingress:
  release_name: nginx-ingress
  release_namespace: gpii
cert-manager:
  release_name: cert-manager
  release_namespace: kube-system
k8s-snapshots:
  release_name: k8s-snapshots
  release_namespace: kube-system
gpii-dataloader:
  release_name: dataloader
  release_namespace: gpii
gpii-preferences:
  release_name: preferences
  release_namespace: gpii
gpii-flowmanager:
  release_name: flowmanager
  release_namespace: gpii
# fluentd:
#   release_name: preferences
#   release_namespace: gpii
