apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: kube-system
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: webmaster@raisingthefloor.org
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}
