# Default values for backup-exporter
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: google/cloud-sdk
  tag: 242.0.0-alpine
  pullPolicy: IfNotPresent

nameOverride: backup-exporter

serviceAccountName: ""

destinationBucket: ""

localIntermediateBucket: ""

replicaCount: 2

schedule: "0 0 * * *"

logBucket: ""
