Name: locust

image:
  repository: gpii/locust
  tag: 0.9.0-gpii.4
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  name: master-web
  type: NodePort
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
  annotations: {}
  extraLabels: {}

master:
  config:
    target-host: https://site.example.com
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

worker:
  config:
    # all files from tasks folder are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/tasks.py"
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  target:
    labels:
    namespace: gpii
