apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "preferences.name" . }}-ingress
  {{- if .Values.ingress.disableSslRedirect }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  {{- end }}
spec:
  tls:
    - hosts:
      {{ toYaml .Values.dnsNames | indent 6 }}
      secretName: {{ template "preferences.name" . }}-tls
  rules:
    - host: {{ .Values.dnsNames | first }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "preferences.name" . }}
            servicePort: {{ .Values.svcListenPort }}
