# Default values for backup-exporter
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: google/cloud-sdk
  tag: 241.0.0-alpine
  pullPolicy: IfNotPresent

replicaCount: ${replica_count}

serviceAccountName: "${service_account_name}"

destinationBucket: "${destination_bucket}"

schedule: "${schedule}"
