apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "preferences.name" . }}-cert
spec:
  secretName: {{ template "preferences.name" . }}-tls
  issuerRef:
    name: letsencrypt-{{ template "preferences.name" . }}
    kind: Issuer
  dnsNames:
  {{ toYaml .Values.dnsNames | indent 2 | trim }}
  acme:
    config:
    - dns01:
        provider: default
      domains:
      {{ toYaml .Values.dnsNames | indent 6 | trim }}
