apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "preferences.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: preferences
    spec:
      containers:
      - name: preferences
        image: "{{ .Values.image.repository }}@{{ .Values.image.checksum }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.preferencesListenPort }}
        env:
        - name: NODE_ENV
          value: {{ .Values.nodeEnv }}
        - name: GPII_PREFERENCESSERVER_LISTEN_PORT
          value: '{{ .Values.preferencesListenPort }}'
        - name: GPII_DATASOURCE_HOSTNAME
          value:  '{{ .Values.datasourceHostname }}'
        - name: GPII_DATASOURCE_PORT
          value: '{{ .Values.datasourceListenPort }}'
        {{- if .Values.enableStackdriverTrace }}
        - name: GPII_ENABLE_STACKDRIVER_TRACE
          value: 'true'
        {{- end }}
        {{- if .Values.credentialsSecretName }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/credentials.json
        volumeMounts:
        - name: credentials
          mountPath: /etc/credentials
          readOnly: true
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{ toYaml .Values.resources | indent 10 | trim }}
        {{- end }}
        livenessProbe:
          exec:
            command:
            - '/usr/bin/curl'
            - '-f'
            - 'http://localhost:{{ .Values.preferencesListenPort }}/health'
        readinessProbe:
          exec:
            command:
            - '/usr/bin/curl'
            - '-f'
            - 'http://localhost:{{ .Values.preferencesListenPort }}/ready'
      {{- if .Values.credentialsSecretName }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ .Values.credentialsSecretName }}
      {{- end }}
