# Default values for gpii-preferences.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

svcListenPort: 80
preferencesListenPort: 8081
datasourceListenPort: 5984
datasourceHostname: "http://admin:password@couchdb-svc-couchdb.gpii.svc.cluster.local"

couchdb:
  labels:
    app: couchdb
  port: http-couchdb

nodeEnv: gpii.config.preferencesServer.standalone.production

enableStackdriverTrace: false

image:
  repository: gpii/universal
  checksum: sha256:652ed9dc86639d51e806356737567336339c9eb675193ba04b2c5346de3bdee6
  pullPolicy: IfNotPresent

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

nameOverride: preferences

## Optional resource requests and limits for deployment
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  # limits:
  #  cpu: 56
  #  memory: 256Gi
