# Default values for gpii-preferences.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

svc_listen_port: 80
preferences_listen_port: 8081
datasource_listen_port: 5984
datasource_hostname: "http://admin:password@couchdb-svc-couchdb.gpii.svc.cluster.local"

node_env: gpii.config.preferencesServer.standalone.production

image:
  repository: gpii/universal
  checksum: sha256:8547f22ae8e86d7b4b09e10d9ec87b1605b47dc37904171c84555a55462f161e
  pullPolicy: IfNotPresent

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 0

issuerRef:
  name: letsencrypt-production
  kind: Issuer

dnsNames:
- preferences.test.local

secretKeyRef:
  name: couchdb-secrets
  key: datasource_hostname

ingress:
  disable_ssl_redirect: false

nameOverride: preferences

## Optional resource requests and limits for deployment
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  # limits:
  #  cpu: 56
  #  memory: 256Gi
